#!/bin/sh

rsync -a --itemize-changes bin/. $HOME/bin/.
rsync -a --itemize-changes etc/. $HOME/etc/.

# install perl, python and anything else
brew update
brew bundle

# install perl dependencies
cpanm $(cat cpanm.txt)

# install python dependencies
/usr/local/opt/python/libexec/bin/pip install -r requirements.txt

# turn off perl-window session saving introduced in a recent macOS
# (as found in /etc/bashrc_Apple_Terminal)
touch $HOME/.bash_sessions_disable
